### ISSUE TITLE
Problem with administrator sign-in

### ISSUE THREAD

**Issue by effidoc** [welimir/arfooo#1]
Hello, thanks to continue to improve arfooo script, I installed your zip some weeks ago, and it repair the damaged caused by php upgrade on my servor.
But now I cannot signin with the admin , I asked for a new password, but impossible to enter. Did someone encounter this issue ?

**Comment by mkwl** [comment]
Hello effidoc,
no, this issue is unknown, but a rewrite problem was the first I thought about. Please examine your apache error log, if possible, in debug mode to see where it tries to route /admin/main/logIn.

**Comment by effidoc** [comment]
well, i changed password in database and everything fine now thank you for the attention
